name: 'Rajat Jindal'
description: 'downloads and add fermyon/spin to your PATH'
author: 'Rajat Jindal'
inputs:
  github_token:
    required: true
    description: 'to update comment on pr'
  fermyon_token_file:
    required: false
    description: 'file that contains fermyon token details, defaults to ${process.env.GITHUB_WORKSPACE}/config.json'
runs:
  using: 'node16'
  main: 'dist/index.js'
